# Generated by Django 5.1 on 2026-07-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admit_cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="batch",
            field=models.CharField(
                blank=True, default="Batch 2026", max_length=100, null=True
            ),
        ),
    ]
